default:
	javac *.java

server:
	java NakovChatServer chathub.jks password

alice:
	java NakovChatClient alice.jks password

bob:
	java NakovChatClient bob.jks password

charles:
	java NakovChatClient charles.jks password

david:
	java NakovChatClient david.jks password

clean:
	rm *.class
